# Generated by Django 2.1.7 on 2019-05-21 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_users', '0001_initial'),
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.TextField()),
                ('class_level', models.IntegerField()),
                ('students', models.ManyToManyField(to='school_users.Student')),
                ('teachers', models.ManyToManyField(to='school_users.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.TextField()),
                ('enrollment_year', models.IntegerField()),
                ('chains', models.ManyToManyField(to='block.Chain')),
                ('classes', models.ManyToManyField(to='school.Class')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_users.Head')),
            ],
        ),
    ]
