# Generated by Django 2.1.5 on 2019-07-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_class_class_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sponte_client_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
