# Generated by Django 2.1.5 on 2019-07-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0008_auto_20190611_1132'),
        ('school', '0004_auto_20190703_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_year',
            new_name='enrollment_class_year',
        ),
        migrations.AddField(
            model_name='school',
            name='adminorsupervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_users.Supervisor'),
        ),
    ]
