# Generated by Django 2.1.5 on 2019-07-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190704_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_level',
            field=models.IntegerField(verbose_name='Nível da classe'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.TextField(verbose_name='Nome da classe'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_unit',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='1', max_length=500, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='school',
            name='adminorsupervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_users.Supervisor', verbose_name='Admin/Supervisor'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='school',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_users.Head', verbose_name='Diretor'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.TextField(verbose_name='Nome da escola'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sponte_client_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número do Cliente Sponte'),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.TextField(blank=True, null=True, verbose_name='Estado'),
        ),
    ]
