# Generated by Django 2.1.5 on 2019-07-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20190704_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sponte_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token do Sponte'),
        ),
    ]
