# Generated by Django 2.1.5 on 2019-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_school_sponte_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sponte_client_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='TellMe ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sponte_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token TellMe'),
        ),
    ]
