# Generated by Django 2.1.5 on 2019-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0008_auto_20190611_1132'),
        ('school', '0008_auto_20190706_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(to='school_users.Student'),
        ),
        migrations.AddField(
            model_name='school',
            name='teachers',
            field=models.ManyToManyField(to='school_users.Teacher'),
        ),
    ]
