# Generated by Django 2.1.5 on 2019-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20190706_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='tell_me_school_id',
            field=models.TextField(blank=True, null=True, verbose_name='Tell School ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sponte_client_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='SPONTE ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sponte_token',
            field=models.TextField(blank=True, null=True, verbose_name='SPONTE Token'),
        ),
    ]
