# Generated by Django 2.1.5 on 2019-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20190707_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_unit',
            field=models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='1', max_length=500, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='class',
            name='enrollment_class_year',
            field=models.IntegerField(default=2019, verbose_name='Ano da classe'),
        ),
    ]
