# Generated by Django 2.1.5 on 2019-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0009_auto_20190707_1518'),
        ('school', '0013_auto_20190708_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='parents',
            field=models.ManyToManyField(to='school_users.Parent'),
        ),
    ]
