# Generated by Django 2.1.5 on 2019-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_school_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='app_name',
            field=models.TextField(blank=True, null=True, verbose_name='Nome do App'),
        ),
    ]
