# Generated by Django 2.1.5 on 2019-07-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_school_app_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_level',
        ),
        migrations.AddField(
            model_name='class',
            name='slm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
