# Generated by Django 2.1.5 on 2019-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20190716_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.TextField(verbose_name='Nome da turma'),
        ),
        migrations.AlterField(
            model_name='class',
            name='enrollment_class_year',
            field=models.IntegerField(default=2019, verbose_name='Ano da turma'),
        ),
    ]
