# Generated by Django 2.1.5 on 2019-07-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20190716_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='slm',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais URL'),
        ),
    ]
