# Generated by Django 2.1.5 on 2019-08-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20190731_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='maple_product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id do Material'),
        ),
    ]
