# Generated by Django 2.1.5 on 2019-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_class_maple_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='maple_product_id',
            field=models.TextField(blank=True, null=True, verbose_name='Id do Material'),
        ),
    ]
