# Generated by Django 2.1.5 on 2019-08-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20190802_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='maple_product_id',
            new_name='sku',
        ),
    ]
