# Generated by Django 2.1.5 on 2019-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20190802_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_unit',
            field=models.CharField(blank=True, choices=[('Integral', 'Integral'), ('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Integral', max_length=500, null=True, verbose_name='Horário'),
        ),
    ]
