# Generated by Django 2.1.11 on 2019-08-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20190803_0822'),
        ('school', '0022_auto_20190803_2122'),
    ]

    operations = [
    ]
