# Generated by Django 2.1.5 on 2019-08-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_merge_20190804_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_unit',
            field=models.CharField(choices=[('Integral', 'Integral'), ('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Integral', max_length=500, null=True, verbose_name='Horário'),
        ),
    ]
