# Generated by Django 2.1.5 on 2019-08-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0019_witness'),
        ('school', '0024_auto_20190806_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='first_witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_witness_school', to='school_users.Witness', verbose_name='Primeira Testemunha'),
        ),
        migrations.AddField(
            model_name='school',
            name='second_witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_witness_school', to='school_users.Witness', verbose_name='Segunda Testemunha'),
        ),
    ]
