# Generated by Django 2.1.5 on 2019-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20190808_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_maple_bear',
            field=models.BooleanField(default=False),
        ),
    ]
