# Generated by Django 2.1.5 on 2019-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0022_auto_20190821_2004'),
        ('school', '0026_school_is_maple_bear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='head',
        ),
        migrations.AddField(
            model_name='school',
            name='heads',
            field=models.ManyToManyField(to='school_users.Head', verbose_name='Diretores'),
        ),
        migrations.AddField(
            model_name='school',
            name='quantity_of_directors',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade de Diretores'),
        ),
    ]
