# Generated by Django 2.1.5 on 2019-09-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0022_auto_20190821_2004'),
        ('school', '0027_auto_20190913_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_head', to='school_users.Head', verbose_name='Diretor'),
        ),
    ]
