# Generated by Django 2.1.5 on 2019-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_remove_school_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='tell_me_school_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TellMe ID'),
        ),
    ]
