# Generated by Django 2.1.5 on 2019-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_auto_20190926_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='school_users.Student', verbose_name='Estudantes'),
        ),
    ]
