# Generated by Django 2.1.5 on 2019-10-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_auto_20191002_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(blank=True, to='school_users.Student', verbose_name='Estudantes'),
        ),
    ]
