# Generated by Django 2.1.5 on 2019-10-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_auto_20191002_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='value_per_contract',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Valor por Contrato'),
        ),
    ]
