# Generated by Django 2.1.7 on 2019-11-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0022_auto_20190821_2004'),
        ('school', '0033_school_value_per_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='adminorsupervisor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminorsupervisor_2', to='school_users.Supervisor', verbose_name='Admin/Supervisor_2'),
        ),
    ]
