# Generated by Django 2.2 on 2020-09-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_school_adminorsupervisor_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='enrollment_class_year',
            field=models.IntegerField(verbose_name='Ano da turma'),
        ),
    ]
