# Generated by Django 2.1.7 on 2019-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0003_auto_20190523_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='name',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
