# Generated by Django 2.1.7 on 2019-06-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0004_auto_20190607_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother',
        ),
        migrations.AddField(
            model_name='parent',
            name='relationship',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_parent', to='school_users.Parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_parent', to='school_users.Parent'),
        ),
    ]
