# Generated by Django 2.1.5 on 2019-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0007_auto_20190611_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='neighborhood',
            new_name='neighborhood_sponte',
        ),
        migrations.AddField(
            model_name='parent',
            name='address_number_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='address_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='bithday_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='cell_phone_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='cep_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='city_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='cpf_or_cnpj_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='gender_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='kind_of_person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='neighborhood_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='note_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='responsible_id_sponte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='rg_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='telephone_sponte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
