# Generated by Django 2.1.5 on 2019-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0009_auto_20190707_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='tell_me_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='head',
            name='tell_me_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='tell_me_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tell_me_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='tell_me_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tell_me_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
