# Generated by Django 2.1.5 on 2019-07-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0012_student_bithday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bithday',
            new_name='birthday',
        ),
    ]
