# Generated by Django 2.1.5 on 2019-08-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0015_auto_20190802_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='maple_bear_user_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
