# Generated by Django 2.1.5 on 2019-08-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0016_auto_20190802_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='third_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_parent', to='school_users.Parent', verbose_name='Segundo Responsável Pedagógico (Opcional)'),
        ),
    ]
