# Generated by Django 2.1.5 on 2019-08-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0017_student_third_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='maple_bear_email',
            field=models.TextField(blank=True, null=True, verbose_name='Email Maple Bear'),
        ),
        migrations.AddField(
            model_name='student',
            name='maple_bear_password',
            field=models.TextField(blank=True, null=True, verbose_name='Senha Maple Bear'),
        ),
        migrations.AddField(
            model_name='student',
            name='maple_bear_user_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='maple_bear_username',
            field=models.TextField(blank=True, null=True, verbose_name='Nome de Usuário Maple Bear'),
        ),
    ]
