# Generated by Django 2.1.5 on 2019-08-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_users', '0018_auto_20190805_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('witness_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=750, null=True)),
                ('rg', models.TextField(blank=True, null=True)),
                ('cpf', models.TextField(blank=True, null=True)),
                ('tell_me_user_id', models.IntegerField(blank=True, null=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
