# Generated by Django 2.1.11 on 2019-08-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0019_witness'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='operation_return_message_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='responsibles_sponte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
