# Generated by Django 2.1.11 on 2019-08-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0021_auto_20190821_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_parent', to='school_users.Parent', verbose_name='Responsável Financeiro'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_parent', to='school_users.Parent', verbose_name='Responsável Pedagógico'),
        ),
    ]
