# Generated by Django 2.1.7 on 2019-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0022_auto_20190821_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='tell_me_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID assinante Tellme'),
        ),
        migrations.AlterField(
            model_name='student',
            name='didatic_responsible_id_sponte',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID parent 2 Tellme'),
        ),
        migrations.AlterField(
            model_name='student',
            name='financial_responsible_id_sponte',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID parent 1 Tellme'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tell_me_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID aluno Tellme'),
        ),
    ]
