# Generated by Django 2.1.5 on 2019-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
