# Generated by Django 2.2 on 2020-08-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20200825_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.Contract'),
        ),
    ]
