# Generated by Django 2.1.7 on 2019-05-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('signed', models.BooleanField(default=False)),
                ('pdf', models.FileField(upload_to='')),
                ('counter_signe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_responsible', to='school_users.Supervisor')),
                ('first_auth_signe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_responsible', to='school_users.Parent')),
                ('second_auth_signe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_responsible', to='school_users.Parent')),
            ],
        ),
    ]
