# Generated by Django 2.1.7 on 2019-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf',
            field=models.FileField(upload_to='../media'),
        ),
    ]
