# Generated by Django 2.1.7 on 2019-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20190523_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='signed',
            new_name='all_signed',
        ),
        migrations.AddField(
            model_name='contract',
            name='counter_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='first_auth_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='second_auth_signed',
            field=models.BooleanField(default=False),
        ),
    ]
