# Generated by Django 2.1.7 on 2019-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20190523_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='counter_signed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='first_auth_signed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='second_auth_signed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
