# Generated by Django 2.1.7 on 2019-06-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20190604_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='class_id_sponte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='class_name_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='closing_date_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_free_class_id_sponte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_id_sponte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_number_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='course_id_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='course_name_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_of_registration_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='financial_launched_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='initial_date_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='name_of_curricular_matrix_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='situation_id_sponte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='situation_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='student_id_sponte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='student_name_sponte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='type_of_registration_sponte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
