# Generated by Django 2.1.5 on 2019-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_auto_20190607_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='counter_auth_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='first_auth_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='second_auth_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
