# Generated by Django 2.1.5 on 2019-06-19 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
        ('contract', '0009_auto_20190613_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='block.Chain'),
        ),
    ]
