# Generated by Django 2.1.5 on 2019-06-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_contract_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='terms_of_contract',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
