# Generated by Django 2.1.5 on 2019-07-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0008_auto_20190611_1132'),
        ('contract', '0011_contract_terms_of_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='director_auth_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='director_signe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_responsible', to='school_users.Head'),
        ),
        migrations.AddField(
            model_name='contract',
            name='director_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='director_signed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='slm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
