# Generated by Django 2.1.5 on 2019-07-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_auto_20190705_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='director_auth_hash',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='director_signe',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='director_signed',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='director_signed_timestamp',
        ),
        migrations.AlterField(
            model_name='contract',
            name='counter_signe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_responsible', to='school_users.Head'),
        ),
    ]
