# Generated by Django 2.1.5 on 2019-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_auto_20190707_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id do Tipo de Contrato Sponte'),
        ),
    ]
