# Generated by Django 2.1.5 on 2019-07-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_auto_20190707_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
