# Generated by Django 2.1.5 on 2019-07-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_contract_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='student_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
