# Generated by Django 2.1.5 on 2019-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_contract_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
