# Generated by Django 2.1.5 on 2019-07-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_contract_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='block.Chain', verbose_name='Cadeia da Turma'),
        ),
    ]
