# Generated by Django 2.1.5 on 2019-07-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_auto_20190716_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='terms_of_contract_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Termos Aditivos do Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms_of_contract',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Termos Aditivos do Contrato'),
        ),
    ]
