# Generated by Django 2.1.5 on 2019-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_auto_20190717_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='terms_of_contract',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Termos Aditivos do Contrato (1)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms_of_contract_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Termos Aditivos do Contrato (2)'),
        ),
    ]
