# Generated by Django 2.1.11 on 2019-08-03 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_auto_20190718_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 21, 22, 5, 307446)),
        ),
        migrations.AddField(
            model_name='contract',
            name='purchased_slm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
