# Generated by Django 2.1.11 on 2019-08-03 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_auto_20190803_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 21, 23, 11, 972354)),
        ),
    ]
