# Generated by Django 2.1.11 on 2019-08-04 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0024_auto_20190803_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 4, 0, 40, 40, 230645)),
        ),
    ]
