# Generated by Django 2.1.11 on 2019-08-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0025_auto_20190804_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
