# Generated by Django 2.1.5 on 2019-08-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0019_witness'),
        ('contract', '0027_auto_20190805_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='first_witness_signe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_witness', to='school_users.Witness'),
        ),
        migrations.AddField(
            model_name='contract',
            name='second_witness_signe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_witness', to='school_users.Witness'),
        ),
        migrations.AddField(
            model_name='contract',
            name='third_auth_signe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_responsible', to='school_users.Parent'),
        ),
    ]
