# Generated by Django 2.1.5 on 2019-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0030_auto_20190809_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
