# Generated by Django 2.1.5 on 2019-10-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0031_contract_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='third_auth_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='third_auth_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='third_auth_signed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
