# Generated by Django 2.2 on 2020-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_auto_20191004_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
