# Generated by Django 2.2 on 2020-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0033_contract_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default='2020-12-31', verbose_name='Data Final do Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicial do Contrato'),
        ),
    ]
