# Generated by Django 2.2 on 2020-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0034_auto_20200915_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.AddField(
            model_name='contract',
            name='end',
            field=models.DateField(blank=True, default='2020-12-31', null=True, verbose_name='Data Final do Contrato'),
        ),
        migrations.AddField(
            model_name='contract',
            name='expiration',
            field=models.DateField(blank=True, default='2020-12-31', null=True, verbose_name='Data Expiração do Contrato'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
