# Generated by Django 2.2 on 2020-09-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0035_auto_20200918_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='expiration',
            field=models.DateField(blank=True, default='2020-12-31', null=True, verbose_name='Data de Expiração de Assinatura do Contrato'),
        ),
    ]
