# Generated by Django 2.2 on 2021-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0036_auto_20200918_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_sent_to_drive',
            field=models.BooleanField(default=False),
        ),
    ]
